version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    target-branch: 'main'
    reviewers:
      - 'Daniil-Oberlev'
    assignees:
      - 'Daniil-Oberlev'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
